[tool.poetry]
name = "streamlit-pills"
version = "0.3.1"
description = "💊 A Streamlit component to show clickable pills/badges"
authors = ["Johannes Rieke <johannes.rieke@gmail.com>"]
license = "MIT"
readme = "README.md"
# This is required so the frontend code is properly included in the wheel. 
include = ["streamlit_pills/frontend/build/**/*"]

[tool.poetry.dependencies]
python = "!=3.9.7,>=3.8"
streamlit = "^1.12.0"

[tool.poetry.dev-dependencies]
watchdog = "^2.1.9"
black = "^22.6.0"
isort = "^5.10.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
